export const  ADD_INGREDIANT = "ADD_INGREDIANT";
export const  REMOVE_INGREDIANT = "REMOVE_INGREDIANT";
export const  SET_INGREDIANT = "SET_INGREDIANT";
export const SET_FETCH_ERROR =  "SET_FETCH_ERROR";

export const PURCHASE_BURGUR_START = "PURCHASE_BURGUR_START"; 
export const BURGER_PURCHASE_SUCCESS = "BURGER_PURCHASE_SUCCESS";
export const BURGER_PURCHASE_FAIL = "BURGER_PURCHASE_FAIL";
export const BURGER_INIT = "BURGER_INIT";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT"; 

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";